// <auto-generated />
using System;
using HelpDesk.Domain.Chamados;
using HelpDesk.Domain.Triagem;
using HelpDesk.Infrastructure.Persistencia;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Pgvector;

#nullable disable

namespace HelpDesk.Infrastructure.Migrations
{
    [DbContext(typeof(HelpDeskDbContext))]
    [Migration("20261001183504_Rag")]
    partial class Rag
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "prioridade_chamado", new[] { "baixa", "media", "alta", "critica" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "status_chamado", new[] { "aberto", "em_andamento", "resolvido", "fechado", "cancelado" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "status_triagem", new[] { "pendente", "concluida", "falhou", "aceita", "rejeitada" });
            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "pg_trgm");
            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "unaccent");
            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "vector");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("HelpDesk.Domain.Categorias.Categoria", b =>
                {
                    b.Property<short>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<short>("Id"));

                    b.Property<DateTimeOffset>("CriadoEm")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("criado_em")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)")
                        .HasColumnName("nome");

                    b.HasKey("Id")
                        .HasName("pk_categorias");

                    b.HasIndex("Nome")
                        .IsUnique()
                        .HasDatabaseName("ix_categorias_nome");

                    b.ToTable("categorias", (string)null);
                });

            modelBuilder.Entity("HelpDesk.Domain.Chamados.Chamado", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("AtualizadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("atualizado_em");

                    b.Property<short?>("CategoriaId")
                        .HasColumnType("smallint")
                        .HasColumnName("categoria_id");

                    b.Property<DateTimeOffset>("CriadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("criado_em");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("descricao");

                    b.Property<long>("Numero")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("numero");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<long>("Numero"));

                    b.Property<Prioridade>("Prioridade")
                        .HasColumnType("prioridade_chamado")
                        .HasColumnName("prioridade");

                    b.Property<DateTimeOffset?>("ResolvidoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("resolvido_em");

                    b.Property<string>("SolicitanteEmail")
                        .IsRequired()
                        .HasMaxLength(254)
                        .HasColumnType("character varying(254)")
                        .HasColumnName("solicitante_email");

                    b.Property<string>("SolicitanteNome")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("solicitante_nome");

                    b.Property<StatusChamado>("Status")
                        .HasColumnType("status_chamado")
                        .HasColumnName("status");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("titulo");

                    b.Property<uint>("Versao")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id")
                        .HasName("pk_chamados");

                    b.HasIndex("Numero")
                        .IsUnique()
                        .HasDatabaseName("ux_chamados_numero");

                    b.HasIndex("CategoriaId", "CriadoEm")
                        .IsDescending(false, true)
                        .HasDatabaseName("ix_chamados_categoria_id_criado_em");

                    b.HasIndex("CriadoEm", "Id")
                        .IsDescending()
                        .HasDatabaseName("ix_chamados_criado_em_id");

                    b.HasIndex("Prioridade", "CriadoEm")
                        .IsDescending()
                        .HasDatabaseName("ix_chamados_prioridade_criado_em");

                    b.HasIndex("Status", "CriadoEm")
                        .IsDescending(false, true)
                        .HasDatabaseName("ix_chamados_status_criado_em");

                    b.ToTable("chamados", null, t =>
                        {
                            t.HasCheckConstraint("ck_chamados_critica_nao_cancelada", "NOT (prioridade = 'critica' AND status = 'cancelado')");

                            t.HasCheckConstraint("ck_chamados_descricao_tamanho", "char_length(descricao) BETWEEN 10 AND 5000");

                            t.HasCheckConstraint("ck_chamados_resolvido_em_apos_criacao", "resolvido_em IS NULL OR resolvido_em >= criado_em");

                            t.HasCheckConstraint("ck_chamados_resolvido_em_coerente", "(resolvido_em IS NOT NULL) = (status IN ('resolvido', 'fechado'))");

                            t.HasCheckConstraint("ck_chamados_solicitante_email_formato", "solicitante_email ~* '^[^@\\s]+@[^@\\s]+\\.[^@\\s]+$'");

                            t.HasCheckConstraint("ck_chamados_titulo_tamanho", "char_length(titulo) BETWEEN 5 AND 150");
                        });
                });

            modelBuilder.Entity("HelpDesk.Domain.Chamados.Comentario", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Autor")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("autor");

                    b.Property<Guid>("ChamadoId")
                        .HasColumnType("uuid")
                        .HasColumnName("chamado_id");

                    b.Property<DateTimeOffset>("CriadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("criado_em");

                    b.Property<string>("Texto")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("texto");

                    b.HasKey("Id")
                        .HasName("pk_comentarios");

                    b.HasIndex("ChamadoId", "CriadoEm")
                        .HasDatabaseName("ix_comentarios_chamado_id_criado_em");

                    b.ToTable("comentarios", null, t =>
                        {
                            t.HasCheckConstraint("ck_comentarios_texto_tamanho", "char_length(texto) BETWEEN 1 AND 4000");
                        });
                });

            modelBuilder.Entity("HelpDesk.Domain.Chamados.HistoricoStatus", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<long>("Id"));

                    b.Property<DateTimeOffset>("AlteradoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("alterado_em");

                    b.Property<string>("AlteradoPor")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("alterado_por");

                    b.Property<Guid>("ChamadoId")
                        .HasColumnType("uuid")
                        .HasColumnName("chamado_id");

                    b.Property<StatusChamado?>("StatusAnterior")
                        .HasColumnType("status_chamado")
                        .HasColumnName("status_anterior");

                    b.Property<StatusChamado>("StatusNovo")
                        .HasColumnType("status_chamado")
                        .HasColumnName("status_novo");

                    b.HasKey("Id")
                        .HasName("pk_historico_status");

                    b.HasIndex("ChamadoId", "AlteradoEm")
                        .HasDatabaseName("ix_historico_status_chamado_id_alterado_em");

                    b.ToTable("historico_status", null, t =>
                        {
                            t.HasCheckConstraint("ck_historico_status_muda_status", "status_anterior IS DISTINCT FROM status_novo");
                        });
                });

            modelBuilder.Entity("HelpDesk.Domain.Conhecimento.ArtigoConhecimento", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("Ativo")
                        .HasColumnType("boolean")
                        .HasColumnName("ativo");

                    b.Property<DateTimeOffset>("AtualizadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("atualizado_em");

                    b.Property<short?>("CategoriaId")
                        .HasColumnType("smallint")
                        .HasColumnName("categoria_id");

                    b.Property<string>("Conteudo")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("conteudo");

                    b.Property<DateTimeOffset>("CriadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("criado_em");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("titulo");

                    b.HasKey("Id")
                        .HasName("pk_artigos_conhecimento");

                    b.HasIndex("CategoriaId")
                        .HasDatabaseName("ix_artigos_conhecimento_categoria_id");

                    b.ToTable("artigos_conhecimento", null, t =>
                        {
                            t.HasCheckConstraint("ck_artigos_conhecimento_conteudo_preenchido", "char_length(btrim(conteudo)) > 0");

                            t.HasCheckConstraint("ck_artigos_conhecimento_titulo_preenchido", "char_length(btrim(titulo)) > 0");
                        });
                });

            modelBuilder.Entity("HelpDesk.Domain.Triagem.TriagemIA", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<short?>("CategoriaSugeridaId")
                        .HasColumnType("smallint")
                        .HasColumnName("categoria_sugerida_id");

                    b.Property<Guid>("ChamadoId")
                        .HasColumnType("uuid")
                        .HasColumnName("chamado_id");

                    b.Property<DateTimeOffset?>("ConcluidaEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("concluida_em");

                    b.Property<decimal?>("Confianca")
                        .HasPrecision(4, 3)
                        .HasColumnType("numeric(4,3)")
                        .HasColumnName("confianca");

                    b.Property<DateTimeOffset>("CriadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("criado_em");

                    b.Property<DateTimeOffset?>("DecididaEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("decidida_em");

                    b.Property<string>("DecididaPor")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("decidida_por");

                    b.Property<string>("ErroMotivo")
                        .HasColumnType("text")
                        .HasColumnName("erro_motivo");

                    b.Property<DateTimeOffset?>("LockExpiraEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("lock_expira_em");

                    b.Property<string>("Modelo")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("modelo");

                    b.Property<string>("MotivoRejeicao")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("motivo_rejeicao");

                    b.Property<Prioridade?>("PrioridadeSugerida")
                        .HasColumnType("prioridade_chamado")
                        .HasColumnName("prioridade_sugerida");

                    b.Property<string>("PromptVersao")
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("prompt_versao");

                    b.Property<string>("Provedor")
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("provedor");

                    b.Property<DateTimeOffset>("ProximaTentativaEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("proxima_tentativa_em");

                    b.Property<string>("RespostaSugerida")
                        .HasColumnType("text")
                        .HasColumnName("resposta_sugerida");

                    b.Property<string>("Resumo")
                        .HasColumnType("text")
                        .HasColumnName("resumo");

                    b.Property<StatusTriagem>("Status")
                        .HasColumnType("status_triagem")
                        .HasColumnName("status");

                    b.Property<short>("Tentativas")
                        .HasColumnType("smallint")
                        .HasColumnName("tentativas");

                    b.Property<string>("TraceParent")
                        .HasMaxLength(55)
                        .HasColumnType("character varying(55)")
                        .HasColumnName("trace_parent");

                    b.Property<uint>("Versao")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id")
                        .HasName("pk_triagens_ia");

                    b.HasIndex("CategoriaSugeridaId")
                        .HasDatabaseName("ix_triagens_ia_categoria_sugerida_id");

                    b.HasIndex("ChamadoId")
                        .IsUnique()
                        .HasDatabaseName("ux_triagens_ia_uma_pendente_por_chamado")
                        .HasFilter("status = 'pendente'");

                    b.HasIndex("ProximaTentativaEm")
                        .HasDatabaseName("ix_triagens_ia_fila")
                        .HasFilter("status = 'pendente'");

                    b.HasIndex("ChamadoId", "CriadoEm")
                        .IsDescending(false, true)
                        .HasDatabaseName("ix_triagens_ia_chamado_id_criado_em");

                    b.ToTable("triagens_ia", null, t =>
                        {
                            t.HasCheckConstraint("ck_triagens_ia_confianca_faixa", "confianca IS NULL OR confianca BETWEEN 0 AND 1");

                            t.HasCheckConstraint("ck_triagens_ia_decisao_coerente", "(status IN ('aceita', 'rejeitada')) = (decidida_em IS NOT NULL)");

                            t.HasCheckConstraint("ck_triagens_ia_execucao_registrada", "status = 'pendente' OR (provedor IS NOT NULL AND modelo IS NOT NULL AND prompt_versao IS NOT NULL)");

                            t.HasCheckConstraint("ck_triagens_ia_falha_com_motivo", "status <> 'falhou' OR erro_motivo IS NOT NULL");

                            t.HasCheckConstraint("ck_triagens_ia_resumo_tamanho", "resumo IS NULL OR char_length(resumo) <= 200");

                            t.HasCheckConstraint("ck_triagens_ia_sugestao_completa", "status NOT IN ('concluida', 'aceita', 'rejeitada') OR (categoria_sugerida_id IS NOT NULL AND prioridade_sugerida IS NOT NULL AND resumo IS NOT NULL AND resposta_sugerida IS NOT NULL AND confianca IS NOT NULL)");
                        });
                });

            modelBuilder.Entity("HelpDesk.Infrastructure.Persistencia.DocumentoRag", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("ArtigoId")
                        .HasColumnType("uuid")
                        .HasColumnName("artigo_id");

                    b.Property<short?>("CategoriaId")
                        .HasColumnType("smallint")
                        .HasColumnName("categoria_id");

                    b.Property<Guid?>("ChamadoId")
                        .HasColumnType("uuid")
                        .HasColumnName("chamado_id");

                    b.Property<short>("ChunkIndice")
                        .HasColumnType("smallint")
                        .HasColumnName("chunk_indice");

                    b.Property<string>("ConteudoMascarado")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("conteudo_mascarado");

                    b.Property<Vector>("Embedding")
                        .HasColumnType("vector(768)")
                        .HasColumnName("embedding");

                    b.Property<string>("EmbeddingModelo")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("embedding_modelo");

                    b.Property<string>("HashConteudo")
                        .IsRequired()
                        .HasColumnType("char(64)")
                        .HasColumnName("hash_conteudo");

                    b.Property<DateTimeOffset?>("IndexadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("indexado_em");

                    b.HasKey("Id")
                        .HasName("pk_documentos_rag");

                    b.HasIndex("ArtigoId")
                        .HasDatabaseName("ix_documentos_rag_artigo_id");

                    b.HasIndex("Embedding")
                        .HasDatabaseName("ix_documentos_rag_embedding_hnsw");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("Embedding"), "hnsw");
                    NpgsqlIndexBuilderExtensions.HasOperators(b.HasIndex("Embedding"), new[] { "vector_cosine_ops" });

                    b.HasIndex("IndexadoEm")
                        .HasDatabaseName("ix_documentos_rag_fila")
                        .HasFilter("embedding IS NULL");

                    b.HasIndex("ChamadoId", "ArtigoId", "ChunkIndice")
                        .IsUnique()
                        .HasDatabaseName("ux_documentos_rag_origem_chunk");

                    NpgsqlIndexBuilderExtensions.AreNullsDistinct(b.HasIndex("ChamadoId", "ArtigoId", "ChunkIndice"), false);

                    b.ToTable("documentos_rag", null, t =>
                        {
                            t.HasCheckConstraint("ck_documentos_rag_chunk_do_chamado", "chamado_id IS NULL OR chunk_indice = 0");

                            t.HasCheckConstraint("ck_documentos_rag_chunk_indice", "chunk_indice >= 0");

                            t.HasCheckConstraint("ck_documentos_rag_indexacao_coerente", "(embedding IS NULL) = (embedding_modelo IS NULL) AND (embedding IS NULL) = (indexado_em IS NULL)");

                            t.HasCheckConstraint("ck_documentos_rag_uma_origem", "num_nonnulls(chamado_id, artigo_id) = 1");
                        });
                });

            modelBuilder.Entity("HelpDesk.Infrastructure.Persistencia.RegistroUsoLlm", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<long>("Id"));

                    b.Property<Guid?>("ChamadoId")
                        .HasColumnType("uuid")
                        .HasColumnName("chamado_id");

                    b.Property<DateTimeOffset>("CriadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("criado_em");

                    b.Property<string>("ErroTipo")
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("erro_tipo");

                    b.Property<int>("LatenciaMs")
                        .HasColumnType("integer")
                        .HasColumnName("latencia_ms");

                    b.Property<string>("Modelo")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("modelo");

                    b.Property<string>("Operacao")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("operacao");

                    b.Property<string>("Provedor")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("provedor");

                    b.Property<bool>("Sucesso")
                        .HasColumnType("boolean")
                        .HasColumnName("sucesso");

                    b.Property<int?>("TokensEntrada")
                        .HasColumnType("integer")
                        .HasColumnName("tokens_entrada");

                    b.Property<int?>("TokensSaida")
                        .HasColumnType("integer")
                        .HasColumnName("tokens_saida");

                    b.Property<Guid?>("TriagemId")
                        .HasColumnType("uuid")
                        .HasColumnName("triagem_id");

                    b.HasKey("Id")
                        .HasName("pk_uso_llm");

                    b.HasIndex("CriadoEm")
                        .HasDatabaseName("ix_uso_llm_criado_em");

                    b.HasIndex("TriagemId")
                        .HasDatabaseName("ix_uso_llm_triagem_id");

                    b.ToTable("uso_llm", null, t =>
                        {
                            t.HasCheckConstraint("ck_uso_llm_erro_coerente", "sucesso = (erro_tipo IS NULL)");

                            t.HasCheckConstraint("ck_uso_llm_operacao", "operacao IN ('triagem', 'copiloto', 'embedding')");

                            t.HasCheckConstraint("ck_uso_llm_valores_positivos", "latencia_ms >= 0 AND (tokens_entrada IS NULL OR tokens_entrada >= 0) AND (tokens_saida IS NULL OR tokens_saida >= 0)");
                        });
                });

            modelBuilder.Entity("HelpDesk.Domain.Chamados.Chamado", b =>
                {
                    b.HasOne("HelpDesk.Domain.Categorias.Categoria", null)
                        .WithMany()
                        .HasForeignKey("CategoriaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_chamados_categorias_categoria_id");
                });

            modelBuilder.Entity("HelpDesk.Domain.Chamados.Comentario", b =>
                {
                    b.HasOne("HelpDesk.Domain.Chamados.Chamado", null)
                        .WithMany("Comentarios")
                        .HasForeignKey("ChamadoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_comentarios_chamados_chamado_id");
                });

            modelBuilder.Entity("HelpDesk.Domain.Chamados.HistoricoStatus", b =>
                {
                    b.HasOne("HelpDesk.Domain.Chamados.Chamado", null)
                        .WithMany("Historico")
                        .HasForeignKey("ChamadoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_historico_status_chamados_chamado_id");
                });

            modelBuilder.Entity("HelpDesk.Domain.Conhecimento.ArtigoConhecimento", b =>
                {
                    b.HasOne("HelpDesk.Domain.Categorias.Categoria", null)
                        .WithMany()
                        .HasForeignKey("CategoriaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_artigos_conhecimento_categorias_categoria_id");
                });

            modelBuilder.Entity("HelpDesk.Domain.Triagem.TriagemIA", b =>
                {
                    b.HasOne("HelpDesk.Domain.Categorias.Categoria", null)
                        .WithMany()
                        .HasForeignKey("CategoriaSugeridaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_triagens_ia_categorias_categoria_sugerida_id");

                    b.HasOne("HelpDesk.Domain.Chamados.Chamado", null)
                        .WithMany()
                        .HasForeignKey("ChamadoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_triagens_ia_chamados_chamado_id");
                });

            modelBuilder.Entity("HelpDesk.Infrastructure.Persistencia.DocumentoRag", b =>
                {
                    b.HasOne("HelpDesk.Domain.Conhecimento.ArtigoConhecimento", null)
                        .WithMany()
                        .HasForeignKey("ArtigoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("fk_documentos_rag_artigos_conhecimento_artigo_id");

                    b.HasOne("HelpDesk.Domain.Chamados.Chamado", null)
                        .WithMany()
                        .HasForeignKey("ChamadoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("fk_documentos_rag_chamados_chamado_id");
                });

            modelBuilder.Entity("HelpDesk.Infrastructure.Persistencia.RegistroUsoLlm", b =>
                {
                    b.HasOne("HelpDesk.Domain.Triagem.TriagemIA", null)
                        .WithMany()
                        .HasForeignKey("TriagemId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_uso_llm_triagens_ia_triagem_id");
                });

            modelBuilder.Entity("HelpDesk.Domain.Chamados.Chamado", b =>
                {
                    b.Navigation("Comentarios");

                    b.Navigation("Historico");
                });
#pragma warning restore 612, 618
        }
    }
}
