// <auto-generated />
using System;
using HelpDesk.Domain.Chamados;
using HelpDesk.Infrastructure.Persistencia;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace HelpDesk.Infrastructure.Migrations
{
    [DbContext(typeof(HelpDeskDbContext))]
    [Migration("20261001123202_Chamados")]
    partial class Chamados
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "prioridade_chamado", new[] { "baixa", "media", "alta", "critica" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "status_chamado", new[] { "aberto", "em_andamento", "resolvido", "fechado", "cancelado" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "status_triagem", new[] { "pendente", "concluida", "falhou", "aceita", "rejeitada" });
            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "pg_trgm");
            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "unaccent");
            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "vector");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("HelpDesk.Domain.Categorias.Categoria", b =>
                {
                    b.Property<short>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<short>("Id"));

                    b.Property<DateTimeOffset>("CriadoEm")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("criado_em")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)")
                        .HasColumnName("nome");

                    b.HasKey("Id")
                        .HasName("pk_categorias");

                    b.HasIndex("Nome")
                        .IsUnique()
                        .HasDatabaseName("ix_categorias_nome");

                    b.ToTable("categorias", (string)null);
                });

            modelBuilder.Entity("HelpDesk.Domain.Chamados.Chamado", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("AtualizadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("atualizado_em");

                    b.Property<short?>("CategoriaId")
                        .HasColumnType("smallint")
                        .HasColumnName("categoria_id");

                    b.Property<DateTimeOffset>("CriadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("criado_em");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("descricao");

                    b.Property<long>("Numero")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("numero");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<long>("Numero"));

                    b.Property<Prioridade>("Prioridade")
                        .HasColumnType("prioridade_chamado")
                        .HasColumnName("prioridade");

                    b.Property<DateTimeOffset?>("ResolvidoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("resolvido_em");

                    b.Property<string>("SolicitanteEmail")
                        .IsRequired()
                        .HasMaxLength(254)
                        .HasColumnType("character varying(254)")
                        .HasColumnName("solicitante_email");

                    b.Property<string>("SolicitanteNome")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("solicitante_nome");

                    b.Property<StatusChamado>("Status")
                        .HasColumnType("status_chamado")
                        .HasColumnName("status");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("titulo");

                    b.Property<uint>("Versao")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id")
                        .HasName("pk_chamados");

                    b.HasIndex("Numero")
                        .IsUnique()
                        .HasDatabaseName("ux_chamados_numero");

                    b.HasIndex("CategoriaId", "CriadoEm")
                        .IsDescending(false, true)
                        .HasDatabaseName("ix_chamados_categoria_id_criado_em");

                    b.HasIndex("CriadoEm", "Id")
                        .IsDescending()
                        .HasDatabaseName("ix_chamados_criado_em_id");

                    b.HasIndex("Prioridade", "CriadoEm")
                        .IsDescending()
                        .HasDatabaseName("ix_chamados_prioridade_criado_em");

                    b.HasIndex("Status", "CriadoEm")
                        .IsDescending(false, true)
                        .HasDatabaseName("ix_chamados_status_criado_em");

                    b.ToTable("chamados", null, t =>
                        {
                            t.HasCheckConstraint("ck_chamados_critica_nao_cancelada", "NOT (prioridade = 'critica' AND status = 'cancelado')");

                            t.HasCheckConstraint("ck_chamados_descricao_tamanho", "char_length(descricao) BETWEEN 10 AND 5000");

                            t.HasCheckConstraint("ck_chamados_resolvido_em_apos_criacao", "resolvido_em IS NULL OR resolvido_em >= criado_em");

                            t.HasCheckConstraint("ck_chamados_resolvido_em_coerente", "(resolvido_em IS NOT NULL) = (status IN ('resolvido', 'fechado'))");

                            t.HasCheckConstraint("ck_chamados_solicitante_email_formato", "solicitante_email ~* '^[^@\\s]+@[^@\\s]+\\.[^@\\s]+$'");

                            t.HasCheckConstraint("ck_chamados_titulo_tamanho", "char_length(titulo) BETWEEN 5 AND 150");
                        });
                });

            modelBuilder.Entity("HelpDesk.Domain.Chamados.Comentario", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Autor")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("autor");

                    b.Property<Guid>("ChamadoId")
                        .HasColumnType("uuid")
                        .HasColumnName("chamado_id");

                    b.Property<DateTimeOffset>("CriadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("criado_em");

                    b.Property<string>("Texto")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("texto");

                    b.HasKey("Id")
                        .HasName("pk_comentarios");

                    b.HasIndex("ChamadoId", "CriadoEm")
                        .HasDatabaseName("ix_comentarios_chamado_id_criado_em");

                    b.ToTable("comentarios", null, t =>
                        {
                            t.HasCheckConstraint("ck_comentarios_texto_tamanho", "char_length(texto) BETWEEN 1 AND 4000");
                        });
                });

            modelBuilder.Entity("HelpDesk.Domain.Chamados.HistoricoStatus", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<long>("Id"));

                    b.Property<DateTimeOffset>("AlteradoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("alterado_em");

                    b.Property<string>("AlteradoPor")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("alterado_por");

                    b.Property<Guid>("ChamadoId")
                        .HasColumnType("uuid")
                        .HasColumnName("chamado_id");

                    b.Property<StatusChamado?>("StatusAnterior")
                        .HasColumnType("status_chamado")
                        .HasColumnName("status_anterior");

                    b.Property<StatusChamado>("StatusNovo")
                        .HasColumnType("status_chamado")
                        .HasColumnName("status_novo");

                    b.HasKey("Id")
                        .HasName("pk_historico_status");

                    b.HasIndex("ChamadoId", "AlteradoEm")
                        .HasDatabaseName("ix_historico_status_chamado_id_alterado_em");

                    b.ToTable("historico_status", null, t =>
                        {
                            t.HasCheckConstraint("ck_historico_status_muda_status", "status_anterior IS DISTINCT FROM status_novo");
                        });
                });

            modelBuilder.Entity("HelpDesk.Domain.Chamados.Chamado", b =>
                {
                    b.HasOne("HelpDesk.Domain.Categorias.Categoria", null)
                        .WithMany()
                        .HasForeignKey("CategoriaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_chamados_categorias_categoria_id");
                });

            modelBuilder.Entity("HelpDesk.Domain.Chamados.Comentario", b =>
                {
                    b.HasOne("HelpDesk.Domain.Chamados.Chamado", null)
                        .WithMany("Comentarios")
                        .HasForeignKey("ChamadoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_comentarios_chamados_chamado_id");
                });

            modelBuilder.Entity("HelpDesk.Domain.Chamados.HistoricoStatus", b =>
                {
                    b.HasOne("HelpDesk.Domain.Chamados.Chamado", null)
                        .WithMany("Historico")
                        .HasForeignKey("ChamadoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_historico_status_chamados_chamado_id");
                });

            modelBuilder.Entity("HelpDesk.Domain.Chamados.Chamado", b =>
                {
                    b.Navigation("Comentarios");

                    b.Navigation("Historico");
                });
#pragma warning restore 612, 618
        }
    }
}
