<Project Sdk="Microsoft.NET.Sdk.Worker">
  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.Hosting" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\HelpDesk.Application\HelpDesk.Application.csproj" />
    <!-- Só para composição via DI (ADR-0002). -->
    <ProjectReference Include="..\HelpDesk.Infrastructure\HelpDesk.Infrastructure.csproj" />
  </ItemGroup>
</Project>
